'use strict';
const $=id=>document.getElementById(id);
let state=null, category='Combat', search='', expanded=new Set(['auto-clicker','lag-range']), busy=false, toastTimer, capture=null, stopped=false;
const nodes=new Map();
const labels={Combat:'战斗',Visual:'视觉',Movement:'移动',Utility:'实用'};
function el(tag,cls,text){const x=document.createElement(tag);if(cls)x.className=cls;if(text!==undefined)x.textContent=text;return x;}
function keyName(n){if(!n)return 'NONE';if(n>=65&&n<=90||n>=48&&n<=57)return String.fromCharCode(n);if(n>=112&&n<=135)return 'F'+(n-111);if(n>=96&&n<=105)return 'NUM '+(n-96);return ({1:'MOUSE 1',2:'MOUSE 2',4:'MOUSE 3',5:'MOUSE 4',6:'MOUSE 5',16:'SHIFT',17:'CTRL',18:'ALT',32:'SPACE',45:'INS',46:'DEL',9:'TAB',20:'CAPS',37:'LEFT',38:'UP',39:'RIGHT',40:'DOWN',160:'L SHIFT',161:'R SHIFT',162:'L CTRL',163:'R CTRL',164:'L ALT',165:'R ALT'})[n]||'KEY '+n;}
function virtualKey(e){if(/^Key[A-Z]$/.test(e.code))return e.code.charCodeAt(3);if(/^Digit[0-9]$/.test(e.code))return e.code.charCodeAt(5);if(/^Numpad[0-9]$/.test(e.code))return 96+Number(e.code.slice(6));if(/^F([1-9]|1[0-9]|2[0-4])$/.test(e.code))return 111+Number(e.code.slice(1));return ({ShiftLeft:160,ShiftRight:161,ControlLeft:162,ControlRight:163,AltLeft:164,AltRight:165,Space:32,Tab:9,Enter:13,Insert:45,Delete:46,Home:36,End:35,PageUp:33,PageDown:34,ArrowLeft:37,ArrowUp:38,ArrowRight:39,ArrowDown:40,CapsLock:20,Backquote:192,Minus:189,Equal:187,BracketLeft:219,BracketRight:221,Backslash:220,Semicolon:186,Quote:222,Comma:188,Period:190,Slash:191,NumpadMultiply:106,NumpadAdd:107,NumpadSubtract:109,NumpadDecimal:110,NumpadDivide:111})[e.code]||null;}
function display(n){return n===null||n===undefined?'—':Number.isInteger(n)?String(n):String(Number(n.toFixed(3)));}
function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').className='toast'+(error?' error':'');$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
async function api(path,body){const response=await fetch('/api/'+path,{cache:'no-store',signal:AbortSignal.timeout(6000),...(body?{method:'POST',headers:{'Content-Type':'application/json','X-Panel-Token':state.token},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw Error(data.error||'连接失败');return data;}
async function poll(){if(busy||stopped)return;try{state=await api('state');update();}catch(error){$('connection-dot').className='dot error';$('connection-text').textContent='未连接';$('notice').hidden=false;$('notice').textContent='本地服务未连接。请重新打开 Driplite Studio，然后刷新。'+error.message;document.querySelectorAll('[data-field]').forEach(x=>x.disabled=true);}}
async function change(action,body={},message){if(!state||busy)return;busy=true;lockControls(true);try{state=await api(action,{...body,revision:state.revision});update();if(message)toast(message);}catch(error){toast(error.message,true);try{state=await api('state');update();}catch{}}finally{busy=false;lockControls(false);update();}}
function lockControls(lock){document.querySelectorAll('[data-field]').forEach(x=>x.disabled=lock||!state);$('pause').disabled=lock||!state;$('undo').disabled=lock||!state?.undo_available;$('reset-all').disabled=lock||!Object.keys(state?.overrides||{}).length;}
function chosen(id){return Object.hasOwn(state.overrides,id)?state.overrides[id]:state.values[id];}
function openDialog(title,paragraph){$('dialog-content').replaceChildren(el('h2','',title),el('p','',paragraph));$('dialog').showModal();return $('dialog-content');}
function makeModule(module){
 const card=el('article','module');card.dataset.module=module.id;
 const head=el('div','module-head');const info=el('button','help','?');info.setAttribute('aria-label',module.name+' 说明');info.onclick=()=>{openDialog(module.name,module.fields.length?'开关与快捷键来自已识别的原生配置字段。只覆盖你修改的项目，其余项目继续使用加载器配置。':'已识别模块名称，但还没有确认可写配置字段。此模块暂时只显示，不提交猜测值。');};
 const title=el('button','module-title',module.name);title.onclick=()=>toggle(module.id);title.setAttribute('aria-controls','body-'+module.id);
 head.append(info,title);
 const key=module.fields.find(f=>f.kind==='key');let keyButton;
 if(key){keyButton=el('button','keybind','NONE');keyButton.dataset.field=key.id;keyButton.setAttribute('aria-label',module.name+' 快捷键');keyButton.onclick=()=>bindKey(module,key);head.append(keyButton);}
 const enabled=module.fields.find(f=>f.kind==='enabled'),toggleLabel=el('label','switch'),checkbox=el('input');checkbox.type='checkbox';checkbox.setAttribute('aria-label',module.name+' 开关');
 if(enabled){checkbox.dataset.field=enabled.id;checkbox.onchange=()=>change('patch',{values:{[enabled.id]:checkbox.checked?1:0}});}else{checkbox.disabled=true;toggleLabel.title='开关字段尚未确认';}
 toggleLabel.append(checkbox,el('span','switch-track'));head.append(toggleLabel);card.append(head);
 const body=el('div','module-body');body.id='body-'+module.id;const controls=[];
 const keyStatus=el('div','field-readback');if(key)body.append(keyStatus);
 for(const field of module.fields.filter(f=>['boolean','select'].includes(f.kind))){
  const row=el('div','control-row'),label=el('label','field-label',field.label);label.htmlFor='option-'+field.id;
  const input=el(field.kind==='select'?'select':'input','option-input');input.id=label.htmlFor;input.dataset.field=field.id;input.setAttribute('aria-label',module.name+' '+field.label);
  if(field.kind==='boolean')input.type='checkbox';else for(const option of field.options){const o=el('option','',option.label);o.value=option.value;input.append(o);}
  input.onchange=()=>change('patch',{values:{[field.id]:field.kind==='boolean'?Number(input.checked):Number(input.value)}});
  row.append(label,input);body.append(row);controls.push({field,input,row});
 }
 for(const field of module.fields.filter(f=>f.kind==='number')){
  const row=el('div','control-row'),label=el('label','field-label');label.htmlFor='number-'+field.id;label.append(el('span','help','?'),document.createTextNode(field.label));
  const group=el('div','number-control'),slider=el('input','slider');slider.type='range';slider.min=field.min;slider.max=field.max;slider.step=field.step;slider.dataset.field=field.id;slider.setAttribute('aria-label',module.name+' '+field.label);
  const bottom=el('div','number-bottom'),number=el('input','number-input');number.type='number';number.id='number-'+field.id;number.min=field.min;number.max=field.max;number.step=field.step;number.dataset.field=field.id;number.setAttribute('aria-label',module.name+' '+field.label+' 数值');
  const fill=v=>slider.style.setProperty('--fill',Math.max(0,Math.min(100,(v-field.min)/(field.max-field.min)*100))+'%');
  slider.oninput=()=>{number.value=slider.value;fill(Number(slider.value));};
  const commit=value=>{if(!Number.isFinite(value)||value<field.min||value>field.max){toast('请输入 '+field.min+'–'+field.max+' 之间的数值',true);update();return;}change('patch',{values:{[field.id]:value}});};
  slider.onchange=()=>commit(Number(slider.value));number.onchange=()=>{if(number.value.trim()===''){update();return;}commit(Number(number.value));};number.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();number.blur();}};
  bottom.append(number,el('span','',field.unit||''));group.append(slider,bottom);row.append(label,group);body.append(row);
  const readback=el('div','field-readback');body.append(readback);controls.push({field,slider,number,fill,readback,row});
 }
 const unresolved=el('p','module-notice',module.fields.some(f=>f.kind==='number')?'其余参数尚未完成映射。':'数值参数尚未完成映射，当前可控制已识别的开关与快捷键。');if(!module.fields.length)unresolved.textContent='此模块的配置入口尚未确认。';body.append(unresolved);
 const tools=el('div','module-tools'),badge=el('span','badge'),reset=el('button','quiet','恢复此模块');reset.onclick=()=>change('reset',{module:module.id},'已恢复此模块的原配置');tools.append(badge,reset);body.append(tools);card.append(body);
 const expand=el('button','expander');expand.append(el('span','chevron'));expand.setAttribute('aria-label',module.name+' 展开参数');expand.setAttribute('aria-controls',body.id);expand.onclick=()=>toggle(module.id);card.append(expand);
 const node={module,card,title,keyButton,key,keyStatus,checkbox,enabled,controls,badge,reset,expand};nodes.set(module.id,node);return card;
}
function toggle(id){expanded.has(id)?expanded.delete(id):expanded.add(id);const n=nodes.get(id);if(n){const yes=expanded.has(id);n.card.classList.toggle('open',yes);n.title.setAttribute('aria-expanded',String(yes));n.expand.setAttribute('aria-expanded',String(yes));}}
function renderList(){if(!state)return;nodes.clear();$('modules').replaceChildren();const list=state.catalog.modules.filter(m=>search?m.name.toLowerCase().includes(search.toLowerCase()):m.category===category);$('category-title').textContent=search?'搜索结果':category;$('module-count').textContent=list.length+' 个模块'+(search?'':' · '+labels[category]);$('modules').setAttribute('aria-label',(search?'搜索结果':category)+' 模块');
 if(!list.length){$('modules').append(el('div','empty','没有匹配的模块。试试 “Clicker” 或 “ESP”。'));return;}
 const left=el('div','column'),right=el('div','column');for(let i=0;i<list.length;i++)(i%2?right:left).append(makeModule(list[i]));$('modules').append(left,right);update();}
function update(){if(!state)return;document.querySelector('.brand small').textContent='本地控制台 · '+(state.preset||'nice');if(!nodes.size&&!$('modules').querySelector('.empty')){renderList();return;}
 $('connection-dot').className='dot'+(state.connected?' live':' error');$('connection-text').textContent=state.demo?'演示模式':state.connected?'已连接游戏':'等待游戏注入';
 const count=Object.keys(state.overrides).length;$('sync-text').textContent=!state.enabled?'同步已暂停':!count?'正在使用原配置':state.confirmed?'自定义参数已读回':'等待下一次配置回写…';$('sync-detail').textContent=count?count+' 项覆盖':'修改一个参数即可开始';$('pause').textContent=state.enabled?'暂停同步':'恢复同步';
 $('notice').hidden=!state.error&&!state.demo&&!state.persistence_error;if(state.error)$('notice').textContent='正在等待游戏连接，可先编辑并保存配置，注入后会自动连接。'+state.error;if(state.demo)$('notice').textContent='演示模式：页面操作仅作用于本地副本，不会控制游戏。';if(state.persistence_error)$('notice').textContent=state.persistence_error;
 if(!state.connected)$('sync-text').textContent='配置已保存 · 等待连接';
 $('footer-status').textContent=state.demo?'本地演示':`本机连接 · ${state.write_count} 次回写${state.last_write_age!==null?' · '+Math.round(state.last_write_age)+' 秒前':''}`;
 for(const n of nodes.values()){
  const overrides=n.module.fields.filter(f=>Object.hasOwn(state.overrides,f.id));n.card.classList.toggle('overridden',overrides.length>0);n.card.classList.toggle('open',expanded.has(n.module.id));n.title.setAttribute('aria-expanded',String(expanded.has(n.module.id)));n.expand.setAttribute('aria-expanded',String(expanded.has(n.module.id)));
  if(n.enabled)n.checkbox.checked=Boolean(chosen(n.enabled.id));else n.checkbox.checked=Boolean(state.objects[n.module.id]?.enabled);
  if(n.keyButton){n.keyButton.textContent=keyName(chosen(n.key.id));const managed=Object.hasOwn(state.overrides,n.key.id);const actual=state.objects[n.module.id]?.key;n.keyStatus.textContent=managed?(!state.enabled?'快捷键接管已暂停':state.demo?'演示快捷键：'+keyName(chosen(n.key.id)):!state.connected?'已保存快捷键，等待游戏连接':actual!==0?'等待关闭游戏原快捷键，实际：'+keyName(actual):'面板快捷键：'+keyName(chosen(n.key.id))+' · 仅游戏前台生效'):'游戏原生快捷键：'+keyName(actual??state.values[n.key.id]);}
  for(const c of n.controls){const condition=c.field.visible_when;const hidden=condition&&chosen(condition.field)!==condition.value;c.row.hidden=Boolean(hidden);if(c.readback)c.readback.hidden=Boolean(hidden);if(c.input){if(document.activeElement!==c.input){if(c.field.kind==='boolean')c.input.checked=Boolean(chosen(c.field.id));else c.input.value=chosen(c.field.id);}continue;}if(![c.number,c.slider].includes(document.activeElement)){const value=chosen(c.field.id);c.slider.value=value??c.field.min;c.number.value=value??'';c.fill(value??c.field.min);}const actual=state.values[c.field.id],pending=state.enabled&&Object.hasOwn(state.overrides,c.field.id)&&Math.abs(actual-state.overrides[c.field.id])>.001;c.readback.textContent=(!state.connected?'离线参考 ':pending?'等待生效 · 当前 ':'当前读回 ')+display(actual)+' '+(c.field.unit||'');c.readback.classList.toggle('pending',pending);}
  n.badge.textContent=overrides.length?overrides.length+' 项自定义'+(!state.enabled?' · 已暂停':''):n.module.fields.length?'使用原配置':'尚未接入';n.reset.disabled=!overrides.length||busy;
 }
 lockControls(busy);
}
function bindKey(module,field){const panel=openDialog(module.name+' · 快捷键','按一个键设置，或从下方选择。Escape 取消；Backspace 清除。改绑后由本地服务接管，仅游戏处于前台时触发，约 2 秒生效。');const box=el('div','key-capture','等待按键…');box.tabIndex=0;box.setAttribute('aria-label','按下新的快捷键');panel.append(box);capture={field,box};const select=el('select','option-input');select.setAttribute('aria-label','选择快捷键');const placeholder=el('option','','选择常用键…');placeholder.value='';select.append(placeholder);for(const code of [0,1,2,4,5,6,160,161,162,163,164,165,32,...Array.from({length:26},(_,i)=>65+i),...Array.from({length:12},(_,i)=>112+i)]){const option=el('option','',keyName(code));option.value=code;select.append(option);}select.onchange=()=>commitKey(field,Number(select.value));panel.append(select);box.focus();}
function commitKey(field,code){if(busy)return;capture=null;$('dialog').close();change('patch',{values:{[field.id]:code}},'快捷键已保存；切回游戏后测试，约 2 秒生效');}
$('dialog').addEventListener('close',()=>capture=null);
document.addEventListener('keydown',e=>{
 document.body.classList.add('keyboard');
 if(capture){if(e.key==='Escape'){capture=null;return;}if(e.target.tagName==='SELECT')return;e.preventDefault();if(e.repeat||e.isComposing)return;const code=e.key==='Backspace'?0:virtualKey(e);if(code===null){capture.box.textContent='此键暂不支持，请从下方选择';return;}commitKey(capture.field,code);return;}
 if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('dialog').open){e.preventDefault();$('search').focus();}
});document.addEventListener('pointerdown',()=>document.body.classList.remove('keyboard'));
document.querySelectorAll('[data-category]').forEach(button=>{button.onclick=()=>{category=button.dataset.category;search='';$('search').value='';document.querySelectorAll('[data-category]').forEach(x=>x.setAttribute('aria-selected',String(x===button)));renderList();};button.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const tabs=[...document.querySelectorAll('[data-category]')];const i=tabs.indexOf(button);const next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[next].focus();tabs[next].click();};});
$('search').oninput=()=>{search=$('search').value.trim();renderList();};$('refresh').onclick=poll;$('pause').onclick=()=>change('active',{enabled:!state.enabled});$('undo').onclick=()=>change('undo',{},'已撤销上一次修改');
$('reset-all').onclick=()=>{const box=openDialog('恢复原配置','移除本面板的所有字段覆盖。加载器将在下一次回写时恢复原配置；可以使用撤销找回本次设置。');const actions=el('div','dialog-actions'),yes=el('button','primary','恢复原配置');yes.onclick=()=>{$('dialog').close();change('reset',{},'已清除全部覆盖，等待原配置读回');};actions.append(yes);box.append(actions);};
function profileDialog(){const box=openDialog('配置管理','修改会自动保存在本机。可将当前配置另存为命名方案，重启后继续使用；载入配置可以撤销。');
 const name=el('input','profile-name');name.placeholder='配置名称';name.maxLength=48;name.setAttribute('aria-label','配置名称');box.append(name);
 const actions=el('div','dialog-actions'),named=el('button','primary','保存为配置'),save=el('button','secondary','导出 JSON'),load=el('button','secondary','导入 JSON');
 named.onclick=async()=>{await change('profile-save',{name:name.value.trim()},'配置已保存');$('dialog').close();profileDialog();};
 save.onclick=()=>{const blob=new Blob([JSON.stringify({format:'driplite-overrides-v1',values:state.overrides,enabled:state.enabled},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='drip-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('已导出自定义配置');};load.onclick=()=>$('import-file').click();actions.append(named,save,load);box.append(actions);
 const list=el('div','profile-list');for(const item of state.profiles||[]){const row=el('div','profile-row'),title=el('span','',item),use=el('button','secondary','载入'),remove=el('button','quiet','删除');use.setAttribute('aria-label','载入 '+item);remove.setAttribute('aria-label','删除 '+item);use.onclick=async()=>{await change('profile-load',{name:item},'已载入 '+item);$('dialog').close();};remove.onclick=()=>{remove.textContent='确认删除';remove.onclick=async()=>{await change('profile-delete',{name:item},'已删除 '+item);$('dialog').close();profileDialog();};};row.append(title,use,remove);list.append(row);}if(!list.children.length)list.append(el('p','','尚未保存命名配置。'));box.append(list);
}
$('profiles').onclick=profileDialog;
$('import-file').onchange=async()=>{const file=$('import-file').files[0];if(!file)return;try{if(file.size>65536)throw Error('配置文件过大');const data=JSON.parse(await file.text());if(data.format!=='driplite-overrides-v1'||!data.values)throw Error('配置格式不支持');$('dialog').close();await change('import',{values:data.values,...('enabled' in data?{enabled:data.enabled}:{})},'已载入自定义配置');}catch(error){toast(error.message,true);}finally{$('import-file').value='';}};
$('settings').onclick=()=>{const box=openDialog('界面设置','设置只影响本地页面。暂停同步后，游戏会恢复加载器提供的原配置。');const label=el('label','dialog-option','紧凑布局'),input=el('input');input.type='checkbox';input.checked=document.body.classList.contains('compact');input.onchange=()=>{document.body.classList.toggle('compact',input.checked);localStorage.setItem('drip.compact',String(input.checked));};label.append(input);box.append(label);const actions=el('div','dialog-actions'),stop=el('button','secondary','断开并关闭本地服务');stop.onclick=async()=>{try{await api('stop',{revision:state.revision});stopped=true;$('dialog').close();$('connection-text').textContent='已断开';$('connection-dot').className='dot';$('sync-text').textContent='拦截已卸载，原配置将恢复';document.querySelectorAll('button,input').forEach(x=>x.disabled=true);}catch(error){toast(error.message,true);}};actions.append(stop);box.append(actions);};
$('mapping-info').onclick=()=>{const coverage=state.catalog.coverage;const box=openDialog('字段支持情况','模块目录完整，不代表每个模块的全部参数都已还原。新增字段按静态代码定位，尚未全部实测游戏效果。');const list=el('ul','mapping-list');for(const line of [state.catalog.modules.length+' 个模块，'+coverage.writable_fields+' 个可写字段。','Auto Clicker CPS：已验证 25 → 30 → 25。','静态扫描 '+coverage.scanned_storage_offsets+' 个存储位置，'+coverage.unresolved_scanned_offsets+' 个仍未确认语义。','参数范围为编辑器约束；确认读回不等于验证游戏效果。'])list.append(el('li','',line));box.append(list);const details=el('details'),summary=el('summary','','查看待解析字段');details.append(summary);const table=el('div','unresolved-fields');for(const f of coverage.unresolved)table.append(el('div','',f.owner_hint+' · '+f.offset+' · '+f.types.join('/')));details.append(table);box.append(details);};
try{document.body.classList.toggle('compact',localStorage.getItem('drip.compact')==='true');}catch{}
poll();setInterval(poll,1000);
